/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneli;

import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import server.Server;

/**
 *
 * @author Uros
 */
public class PanelStatus extends javax.swing.JPanel {

    private static PanelStatus instanca;
    private Server server;

    /**
     * Creates new form PanelStatus
     */
    private PanelStatus() {
        initComponents();
        btnPokreni.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        btnPokreni = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(388, 265));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 0, 51));
        lblStatus.setText("Server NEAKTIVAN");

        btnPokreni.setText("Pokreni server");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnPokreni))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblStatus)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblStatus)
                .addGap(33, 33, 33)
                .addComponent(btnPokreni)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        try {
            if (btnPokreni.isSelected()) {
                server = new Server();
                server.start();
                lblStatus.setText("Server AKTIVAN");
                lblStatus.setForeground(Color.GREEN);
                btnPokreni.setText("Zaustavi server");
            } else {
                server.zaustavi();
                lblStatus.setText("Server NEAKTIVAN");
                lblStatus.setForeground(Color.RED);
                btnPokreni.setText("Pokreni server");
                btnPokreni.setEnabled(false);
                PanelBaza.getInstanca().setSacuvanaBaza(false);
                PanelBaza.getInstanca().otkljucajFormu(true);
                PanelPort.getInstanca().setSacuvanPort(false);
                PanelPort.getInstanca().otkljucajFormu(true);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPokreniActionPerformed

    public static PanelStatus getInstanca() {
        if (instanca == null) {
            instanca = new PanelStatus();
        }
        return instanca;
    }

    public JToggleButton getBtnPokreni() {
        return btnPokreni;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPokreni;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
