/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneli;

import java.io.IOException;
import javax.swing.JOptionPane;
import konfiguracija.Konfiguracija;

/**
 *
 * @author Uros
 */
public class PanelPort extends javax.swing.JPanel {

    private static PanelPort instanca;
    private boolean sacuvanPort = false;

    /**
     * Creates new form PanelPort
     */
    private PanelPort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(288, 265));

        jLabel1.setText("Broj porta:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPort, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            String stringPort = txtPort.getText();
            int intPort = Integer.parseInt(stringPort);
            if (intPort < 0 || intPort > 65565) {
                throw new IOException("Broj porta mora biti celobrojna vrednost izmedju 0 i 65535.");
            }
            Konfiguracija.getInstanca().setProperty("port", stringPort);
            Konfiguracija.getInstanca().sacuvaj();
            sacuvanPort = true;
            otkljucajFormu(false);
            PanelStatus.getInstanca().getBtnPokreni().setEnabled(sacuvanPort && PanelBaza.getInstanca().getSacuvanaBaza());
        } catch (IOException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    public static PanelPort getInstanca() {
        if (instanca == null) {
            instanca = new PanelPort();
        }
        return instanca;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables

    public boolean getSacuvanPort() {
        return sacuvanPort;
    }

    public void setSacuvanPort(boolean sacuvanPort) {
        this.sacuvanPort = sacuvanPort;
    }

    void otkljucajFormu(boolean vrednost) {
        txtPort.setEditable(vrednost);
        btnSacuvaj.setEnabled(vrednost);
    }

}
